# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: scratch

on:

  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

permissions:
  contents: read

jobs:
  build_wheels:
    name: scratch
    runs-on: windows-latest

    steps:

      - name: Install MSYS2
        uses: msys2/setup-msys2@fb197b72ce45fb24f17bf3f807a388985654d1f2 # v2.29
        with:
          msystem: MINGW32
          update: true
          install: git

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: build
        run: bash scratch.sh
        shell: msys2 {0}
